### ISSUE TITLE
(Whatsappweb) Left pannel does not hide anymore.

### ISSUE THREAD

**Issue by pparent76** [alefnode/ubports-apps#39]
Hello,

In current version the left panel (contact panel) does not hide anymore when in a chat, making it difficult to use. On top of that the left panel does not contain contact list by default.

Thank you so much for the work on these apps!

Regards,
Pierre

**Comment by alefnode** [comment]
Working on it, almost done, i am testing new code

**Comment by pparent76** [comment]
Thank you so much!

**Comment by alefnode** [comment]
Fixed https://github.com/alefnode/ubports-apps/commit/c13957fee85a3e01a73f0112a774e38a9ec34180
Updated un open-store for Ubports

**Comment by pparent76** [comment]
Thank you, I just tested, still not working properly for me. See screenshot. I cannot I access conversations when clicking on contacts/groups 
![photo_2024-04-24_15-59-25](https://github.com/alefnode/ubports-apps/assets/12755774/2216cc8c-10e8-4279-b32a-0da4c5c7fa1b)

**Comment by alefnode** [comment]
mmm, i have left bar, i think web changes today and your image uses old one version from Whatsapp Web

**Comment by pparent76** [comment]
It is version 0.2.7

**Comment by alefnode** [comment]
I see webpage like this

![Screenshot from 2024-04-24 16-51-41](https://github.com/alefnode/ubports-apps/assets/19591155/f6bdef48-dbd1-4c36-86c3-0be0d381dd05)

**Comment by pparent76** [comment]
Hum strange, Could possibly the webpage be different depending on the country? Cos your page does not look like the on I get on desktop mode.

I'm in France.

Gracias!

**Comment by mschmids** [comment]
Just want to concur with pparent76, that I am very grateful for the work being done and that I am seeing the same after the update i.e. list of conversations on left side, no conversation content, when selecting individual conversation and list of conversations not hiding. Any other feedback I may be helpful with, please let me know (Xiaomi Mi A2 w/ Xenial/16.04/OTA-25).

**Comment by mschmids** [comment]
Germany, also the desktop (W10 w/ Firefox) layout I have is like yours.

**Comment by alefnode** [comment]
Seems to be a new version, someone tell me in settings you can change to beta version

**Comment by alefnode** [comment]
Maybe using a PC, enable it and then you have it or in other hand wait for this version to be deployed for everyone

**Comment by pparent76** [comment]
Ha but at least I can access the chat with this beta version, so it is much better actually

**Comment by mschmids** [comment]
Huh, switch for beta hidden in help. But yes, works for me as well. Thanks for the helpful discussion.

**Comment by alefnode** [comment]
Close because it was a upgrade from whatsapp for their new web
